name: Trigger Other Repository Workflow

on:
  push:
    branches: [main] # or whichever branch should trigger the workflow

jobs:
  call-reusable-workflow:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: angelomarquesdavinci/release-it-test/.github/workflows/reusable.yml@main
    with:
      branch: main
